hkkf.web/Areas/Admin/Controllers/ShopGroupManangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hkkf.Models;
using hkkf.Repositories;
using JieNuo.Data;
using JieNuo.Data.Exceptions;
using hkkf.web.Areas.Service.Common;

namespace hkkf.web.Areas.Admin.Controllers
{
    [NavigationRoot("店铺班组管理")]
    [SmartAuthorize]
    [SmartMasterPage]
    public class ShopGroupManangeController : Controller
    {
        ShopGroupRepository ShopGroupRepo = new ShopGroupRepository();
        private ShopGroupDetailRepository shopGroupDetailRepo = new ShopGroupDetailRepository();//
        PinFenRepository pinFenRepo = new PinFenRepository();
        private ShopRepository shopRepo = new ShopRepository();//
        PersonShopGroupRepository PersonShopGrupRepo = new PersonShopGroupRepository();

        ShopTempletRepository ShopTempletRepo = new ShopTempletRepository();
        ShopTempletTypeRepository ShopTempletTypeRepo = new ShopTempletTypeRepository();
        ShopTempletDetailsRepository ShopTempletDetailsRepo = new ShopTempletDetailsRepository();

        #region "班组"

        public ActionResult ShopGroupIndex(QueryInfo queryInfo, int[] ids, string name, string alertMessage, string subAction)
        {
            if (subAction == "delete")
            {
                foreach (int userid in ids)
                {
                    ShopGroupRepo.Delete(userid);
                }
                ViewBag.message = "删除成功！";
            }
           
            PagedData<ShopGroups> data = ShopGroupRepo.GetShopGroups(queryInfo, name,this.Users().DepartMent.ID);
            return View(data);
        }
        public ActionResult ShopGroupIndexForFenPei(QueryInfo queryInfo, int[] ids, string name, string alertMessage, string subAction)
        {
            //如果是更新，则更新能做班组的客服
            //首先删除PERSONSHOPGROUP里面的数据，然后添加shopGroupID,如果该班组里面的店铺都由同一个人能够担当，那么就插入该条shopGroupID。
            if (subAction == "update")
            {
                this.PersonShopGrupRepo.updatePersonShopGroup();
            }
            PagedData<ShopGroups> data = ShopGroupRepo.GetShopGroups(queryInfo, name, this.Users().DepartMent.ID);
            return View(data);
        }
        public ActionResult AddShopGroup(int? id)
        {
            Kf_DepartMentRepository kf_DepartRepo = new Kf_DepartMentRepository();
            IEnumerable<SelectListItem> listDepartMent = kf_DepartRepo.GetData(this.Users().DepartMent.ID)
                .Select(p => new SelectListItem
                {
                    Text = p.DepartMentName,
                    Value = p.ID.ToString().Trim(),
                });
            ViewData["listDepartMent"] = listDepartMent;
            if (id != null)
            {
                ShopGroups shopGroup = this.ShopGroupRepo.GetByDatabaseID(id.Value); 
                return View(shopGroup);
            }
            return View();
        }
        //[HttpPost]
        //public ActionResult AddShopGroup(FormCollection collection, string alertMessage, string IsEdit, int? id)
        //{
        //    ShopGroups shopGroup = new ShopGroups();
        //    if (id != null && id.Value > 0)
        //    {
        //        shopGroup = this.ShopGroupRepo.GetByDatabaseID(id.Value);
        //    }     
        //     try
        //    {
        //        if (IsEdit == "1")
        //        {

        //            var shopGroupEdit = this.ShopGroupRepo.GetByDatabaseID(id.Value);
        //            TryUpdateModel(shopGroupEdit, collection);
        //            this.ShopGroupRepo.Update(shopGroupEdit);
        //        }
        //        else
        //        {
        //            TryUpdateModel(shopGroup, collection);
        //            if (this.ShopGroupRepo.ExistShopGroupsName(shopGroup.ShopGroupName))
        //            {
        //                alertMessage = "添加失败 班组名称已存在！";
        //                return View(shopGroup);
        //            }
        //            if (shopGroup.ShopGroupName.IsNullOrEmpty())
        //            {
        //                alertMessage = "班组名不能为空!";
        //                return View(shopGroup);
        //            }
        //            //_shop._User = shopRepository.GetUserByuserName(_User);
        //            //_shop.TotalScore = _shop.DifficutyLevel.ID + _shop.ShopCountLevel.ID;

        //            //_shop._PayCircle = PayCircleRepo.GetByDatabaseID(Convert.ToInt32(collection["_PayCircle"]));
        //            //_shop._Kf_DepartMent = this.kf_DepartMentRepo.GetByDatabaseID(Convert.ToInt32(collection["_Kf_DepartMent"]));
        //            //_shop.DemandUser = this.UserRepository.GetByDatabaseID(Convert.ToInt32(collection["DemandUser"]));
        //            //_shop.SaleUser = UserRepository.GetByDatabaseID(Convert.ToInt32(collection["SaleUser"]));
        //            //_shop.MainKfUser = UserRepository.GetByDatabaseID(Convert.ToInt32(collection["MainKfUser"]));
        //            //_shop._Kf_DepartMent = this.kf_DepartMentRepo.GetByDatabaseID(Convert.ToInt32(collection["_Kf_DepartMent"]));
        //            shopGroup.UpdateTime = System.DateTime.Now;
        //            ShopGroupRepo.Save(shopGroup);
        //        }
        //        alertMessage = "操作成功！";
        //        ViewData["alertMessage"] = alertMessage;
        //        return RedirectToAction("ShopGroupIndex");             
        //    }
        //    catch (RuleException ex)
        //    {
        //        throw new RuleException(ex.Message, ex);
        //    }
        //}
        [HttpPost]
        public ActionResult AddShopGroup(string ShopGroupName, string WorkDayOrNight, string _Kf_DepartMent, int? id)
        {
            //Kf_DepartMentRepository kf_DepartRepo = new Kf_DepartMentRepository();
            //IEnumerable<SelectListItem> listDepartMent = kf_DepartRepo.GetData(this.Users().DepartMent.ID)
            //    .Select(p => new SelectListItem
            //    {
            //        Text = p.DepartMentName,
            //        Value = p.ID.ToString().Trim(),
            //    });
            //ViewData["listDepartMent"] = listDepartMent;
            if (ShopGroupName.IsNullOrEmpty())
                return Json(new { state = false, message = "请填写分组名称！" });
            if (WorkDayOrNight.IsNullOrEmpty())
                return Json(new { state = false, message = "请选择值班类型！" });
            if (_Kf_DepartMent.IsNullOrEmpty())
                return Json(new { state = false, message = "请选择部门！" });

            ShopGroups shopGroup = new ShopGroups();
            if (id != null && id.Value > 0)
            {
                shopGroup = this.ShopGroupRepo.GetByDatabaseID(id.Value);
            }

            try
            {
                //赋值
                shopGroup.ShopGroupName = ShopGroupName;
                shopGroup.WorkDayOrNight = WorkDayOrNight.ToEnum<DayOrNight>();
                shopGroup._Kf_DepartMent = new Kf_DepartMent { ID = _Kf_DepartMent.ToInt() };

                //保存
                if (id != null && id.Value > 0)
                {
                    shopGroup.UpdateTime = System.DateTime.Today;
                    ShopGroupRepo.Update(shopGroup);
                }
                else
                {
                    if (ShopGroupRepo.ExistShopGroupsName(shopGroup.ShopGroupName))
                    {
                        return Json(new { state = false, message = "添加失败 店铺已存在！" });
                    }
                    shopGroup.ContentShops = "无";
                    shopGroup.UpdateTime = System.DateTime.Today;
                    ShopGroupRepo.Save(shopGroup);
                }

                //alertMessage = "操作成功！";
                //ViewData["alertMessage"] = alertMessage;
                //return RedirectToAction("ShopGroupIndex");
                return Json(new { state = true, message = "操作成功！" });
            }
            catch (RuleException ex)
            {
                throw new RuleException(ex.Message, ex);
            }
        }

        public ActionResult Add_ShopGroupDetail(string id)
        {
            ShopGroups shopGroup = this.ShopGroupRepo.GetByDatabaseID(Convert.ToInt32(id));
            //根据shopGroupID取出哪些店铺在shopGroupDetail里面，在前台显示的时候如果在里面的，那么默认为选中。
            List<ShopGroupDetails> listShopGroupDetails = this.shopGroupDetailRepo.GetAll()
                .Where(it => it._ShopGroup == shopGroup)
                .ToList();
            ViewData["listShopGroupDetails"] = listShopGroupDetails;
            ViewData["shopGroup"] = shopGroup;
            var list = shopRepo.GetData(this.Users().DepartMent.ID);          
            return View(list);
        }

        [HttpPost]
        public ActionResult Add_ShopGroupDetail(ShopGroups gp, string[] ids)
        { 

            if (ids!=null&&ids.Length > 0)
            {
                var listShopGroupDetail = this.shopGroupDetailRepo.GetAll()
                    .Where(it => it._ShopGroup == gp);
                foreach (var ShopGroupDetail in listShopGroupDetail)
                {
                    shopGroupDetailRepo.Delete(ShopGroupDetail);
                }
                string strContentShops = "";
                for (int i = 0; i < ids.Length; i++)
                {
                    ShopGroupDetails gd = new ShopGroupDetails()
                    {
                        //_Shop = new Shop { ID = ids[i].ToInt() },                      
                        _Shop=this.shopRepo.GetByDatabaseID(ids[i].ToInt()),
                        _ShopGroup = gp,
                        UpdateTime = DateTime.Now
                    };
                    shopGroupDetailRepo.Save(gd);
                    strContentShops = strContentShops + gd._Shop.Name.Trim() + " | ";
                }
                strContentShops = strContentShops.Substring(0, strContentShops.Trim().Length - 1);
                gp.UpdateTime = System.DateTime.Now;
                gp.ContentShops = strContentShops;

hkkf.web/Areas/Admin/Views/ShopGroupManange/AddShopGroup.cshtml
@using hkkf.Models
@model hkkf.Models.ShopGroups


@{
     
    Layout = null;
}

@*<script type="text/javascript">
    $(function () {
        $("#btnOK").click(function () {
            if ($("#ShopGroupName").attr("value").trim() === "") {
                operationSuccessDialog.html("请输入班组名！");
                operationSuccessDialog.dialog('open');
                return false;
            }
            if ($("#WorkDayOrNightaa").attr("value").trim() === "") {
                operationSuccessDialog.html("请选择值班类型！");
                operationSuccessDialog.dialog('open');
                return false;
            }


        }
        );
    });
 </script>*@

@*@Html.ScriptForModel()
@Html.NavigationBar("店铺班组管理", "添加店铺班组")
@using (Ajax.JQueryBeginForm("AddShopGroup", "ShopGroupManange", new JQueryOptions { UpdateTarget = "#main" }))

{*@
<form method="post" action="@this.Request.Url.AbsoluteUri" class="operatInfoDiv">   
    <table cellspacing="2" cellpadding="0"  >

                <tr>
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.ShopGroupName)：</p>
                    </td>
                    <td colspan="2">
                        @Html.ValueBoxFor(model => model.ShopGroupName)
                        @Html.RequriedMarkFor(model => model.ShopGroupName)
                        @Html.ValidationMessageFor(model => model.ShopGroupName) </td>
                </tr>
                 <tr>
                    <td width="17%" align="right">
                         @Html.DisplayNameFor(model => model.WorkDayOrNight)：
                    </td>
                    <td colspan="2" align=left>
                        @Html.ValueBoxForEnum("WorkDayOrNight", new[] { DayOrNight.白班, DayOrNight.晚班, DayOrNight.全天 },Model==null?"":Model.WorkDayOrNight.ToString(), "请选择") 
                    </td>
                </tr>                 
                     <tr>
                    <td width="17%" align="right">
                        @Html.DisplayNameFor(model => model._Kf_DepartMent)：
                    </td>
                    <td colspan="2" align=left>
                         @Html.DropDownListFor(model => model._Kf_DepartMent, ViewData["listDepartMent"] as IEnumerable<SelectListItem>, Model == null ? "" : Model._Kf_DepartMent.ID.ToString(), "请选择")         
                    </td>
                </tr>
               @* <tr>
                    <td align="right">&nbsp; </td>
                    <td width="23%" height="60">
                        <label>
                            <input type="submit" name="button" id="btnOK" class="button" value="保存" />
                            @if (ViewBag.Edit == "1")
                            {
                                 @Html.Hidden("IsEdit", "1")
                            }
                           
                        </label>
                    </td>
                    <td>
                        <label>
                            @Html.ActionLink("返回", "ShopGroupIndex", "ShopGroupManange", null, new { target = "#main", @class = "button" })
                        </label>
                    </td>
                </tr>*@
    </table>
</form>

hkkf.web/Areas/Admin/Views/ShopGroupManange/AddShopGroup2.cshtml
@using hkkf.Models
@model hkkf.Models.ShopGroups


@{
     
    Layout = null;
}

<script type="text/javascript">
    $(function () {
        $("#btnOK").click(function () {
            if ($("#ShopGroupName").attr("value").trim() === "") {
                operationSuccessDialog.html("请输入班组名！");
                operationSuccessDialog.dialog('open');
                return false;
            }
            if ($("#WorkDayOrNightaa").attr("value").trim() === "") {
                operationSuccessDialog.html("请选择值班类型！");
                operationSuccessDialog.dialog('open');
                return false;
            }


        }
        );
    });
 </script>

@Html.ScriptForModel()
@Html.NavigationBar("店铺班组管理", "添加店铺班组")
@using (Ajax.JQueryBeginForm("AddShopGroup", "ShopGroupManange", new JQueryOptions { UpdateTarget = "#main" }))
{
    <table cellspacing="2" cellpadding="0"  >

                <tr>
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.ShopGroupName)：</p>
                    </td>
                    <td colspan="2">
                        @Html.ValueBoxFor(model => model.ShopGroupName)
                        @Html.RequriedMarkFor(model => model.ShopGroupName)
                        @Html.ValidationMessageFor(model => model.ShopGroupName) </td>
                </tr>
                 <tr>
                    <td width="17%" align="right">
                         @Html.DisplayNameFor(model => model.WorkDayOrNight)：
                    </td>
                    <td colspan="2">
                        @Html.ValueBoxForEnum("WorkDayOrNight", new[] { DayOrNight.白班, DayOrNight.晚班, DayOrNight.全天 }, Model == null ? "" : Model.WorkDayOrNight.ToString(), "请选择") 
                    </td>
                </tr>                 
                     <tr>
                    <td width="17%" align="right">
                        @Html.DisplayNameFor(model => model._Kf_DepartMent)：
                    </td>
                    <td colspan="2">
                         @Html.DropDownListFor(model => model._Kf_DepartMent, ViewData["listDepartMent"] as IEnumerable<SelectListItem>, Model == null ? "" : Model._Kf_DepartMent.DepartMentName.ToString(), "请选择")         
                    </td>
                </tr>
                <tr>
                    <td align="right">&nbsp; </td>
                    <td width="23%" height="60">
                        <label>
                            <input type="submit" name="button" id="btnOK" class="button" value="保存" />
                            @if (ViewBag.Edit == "1")
                            {
                                 @Html.Hidden("IsEdit", "1")
                            }
                           
                        </label>
                    </td>
                    <td>
                        <label>
                            @Html.ActionLink("返回", "ShopGroupIndex", "ShopGroupManange", null, new { target = "#main", @class = "button" })
                        </label>
                    </td>
                </tr>
    </table>
}

hkkf.web/Areas/Admin/Views/ShopGroupManange/ShopGroupIndex.cshtml
@using System
@using System.Collections.Generic
@using System.Linq
@using System.Xml.Serialization
@using DocumentFormat.OpenXml.Spreadsheet
@using hkkf.Models
@using hkkf.Repositories
@using JieNuo.Data;
@model JieNuo.Data.PagedData<hkkf.Models.ShopGroups>

@{
    ViewBag.Title = "店铺班组管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
    $(function () {
        $("#checkBtn").click(function () {
            $("#subAction").attr("value", "check");
        });
    });
 </script>


@Html.NavigationBar("店铺班组信息", " 店铺班组管理")
@using (Ajax.JQueryBeginForm("ShopGroupIndex", "ShopGroupManange", new JQueryOptions { UpdateTarget = "#main" }))
 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺班组名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
        </tr>
    </table>
   
     @Html.AllCheckButton() @Html.AllOtherButton() @Html.AllCancelButton()
    @* @Html.ActionLink("添加店铺班组", "AddShopGroup", "ShopGroupManange", null, new { target = "#main", @class = "button6" })*@
    <a data-opt="add" class="button6" href="/admin/ShopGroupManange/AddShopGroup">添加店铺班组</a>
     @* @Html.ActionLink("删除用户", "DeleteUser", "UsersManage", null, new { target = "#main", @class = "button4" })*@
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr>
                <th></th>
                <th>@Html.DisplayNameForSerialNum() </th>        
                <th>店铺班组名</th>
                <th>白班晚班</th>
                <th>部门</th>
                <th>班组店铺</th>
                <th>班组店铺</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody> 
            @{
    int i = Model.Pager.FristDataPos;  
    }
    @foreach (var item in Model)
    {
<tr>
 <td>@Html.CheckBoxButton(item.ID)</td>
<td>@(i++) </td>
<td>@Html.DisplayValueFor(item, it => it.ShopGroupName)</td>
<td>@Html.DisplayValueFor(item, it => it.WorkDayOrNight)</td>
<td>@Html.DisplayValueFor(item, it => it._Kf_DepartMent)</td>
<td>@Html.Raw(item.ContentShops)</td>
<td> 
   <a data-opt="add" class="add_temps" href="/admin/ShopGroupManange/Add_ShopGroupDetail?id=@item.ID">店铺添加或修改</a>
</td> 
<td>@* @Html.ActionLink("修改", "AddShopGroup", "ShopGroupManange", new { id = item.ID }, new { target = "#main", @class = "button4" })*@
 <a data-opt="add" class="button6" href="/admin/ShopGroupManange/AddShopGroup?id=@item.ID">修改</a>

</td> 
</tr>
    }
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>    
}

hkkf.web/Areas/Admin/Views/ShopGroupManange/ShopGroupIndexForFenPei.cshtml
@using System
@using System.Collections.Generic
@using System.Linq
@using System.Xml.Serialization
@using DocumentFormat.OpenXml.Spreadsheet
@using hkkf.Models
@using hkkf.Repositories
@using JieNuo.Data;
@model JieNuo.Data.PagedData<hkkf.Models.ShopGroups>

@{
    ViewBag.Title = "店铺班组管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
    $(function () {
       // batchMsg("updateBtn");
        $("#updateBtn").click(function () {
            $("#subAction").attr("value", "update");
        });
    });
 </script>


@Html.NavigationBar("店铺班组信息", " 店铺班组管理")
@using (Ajax.JQueryBeginForm("ShopGroupIndexForFenPei", "ShopGroupManange", new JQueryOptions { UpdateTarget = "#main" }))
 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺班组名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "更新", new { id = "updateBtn", @class = "button" })
            </td>
        </tr>
    </table>
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr>
                <th>@Html.DisplayNameForSerialNum() </th>        
                <th>店铺班组名</th>
                <th>部门</th>
                <th>白班晚班</th>
                <th>班组店铺</th>
                <th>客服</th>
            </tr>
        </thead>
        <tbody> 
            @{
                
    int i = Model.Pager.FristDataPos;      
    }
    @foreach (var item in Model)
    {
<tr>
<td>@(i++) </td>
<td>@Html.DisplayValueFor(item, it => it.ShopGroupName)</td>
<td>@Html.DisplayValueFor(item, it => it._Kf_DepartMent)</td>
<td>@Html.DisplayValueFor(item, it => it.WorkDayOrNight)</td>
<td>
  @Html.Raw(item.ContentShops)             
</td>
 <td> 
        @{//根据店铺班组，取出能够做这个班组的客服名单。
        PersonShopGroupRepository PersonShopGroupRepo = new PersonShopGroupRepository();
        List<PersonShopGroup> ListPersonShopGroup = PersonShopGroupRepo.GetAll()
            .Where(it => it._ShopGroups == item)
            .ToList();
            if (ListPersonShopGroup.Count==0||ListPersonShopGroup== null)
            {
                @Html.Raw("无");
            }
            else
            {
                <table>
                @{
                foreach (var PersonShopGroup in ListPersonShopGroup)
                {
                    <tr><td>
                    @Html.Raw(PersonShopGroup._User.ToString())
                    </td></tr>
                }
                }
                </table>
            }                  
        }
    </td> 
</tr>
}
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>
    
}

hkkf.web/Areas/Admin/Views/ShopGroupManange/ShopTempletIndex.cshtml
@using System
@using System.Collections.Generic
@using System.Linq
@using System.Xml.Serialization
@using DocumentFormat.OpenXml.Spreadsheet
@using hkkf.Models
@using hkkf.Repositories
@using JieNuo.Data;
@model JieNuo.Data.PagedData<hkkf.Models.ShopTemplet>

@{
    ViewBag.Title = "排班模板管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
    $(function () {
        $("#checkBtn").click(function () {
            $("#subAction").attr("value", "check");
        });
    });
 </script>


@Html.NavigationBar("排班模板信息", " 模板管理")
@using (Ajax.JQueryBeginForm("ShopTempletIndex", "ShopGroupManange", new JQueryOptions { UpdateTarget = "#main" })) 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺班组名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
            </td>
        </tr>
    </table>
   
     @Html.AllCheckButton() @Html.AllOtherButton() @Html.AllCancelButton()
     <a data-opt="add" class="button6" href="/admin/ShopGroupManange/AddShopTemplet">添加模板</a>
     @*@Html.ActionLink("添加排班模板", "AddShopTemplet", "ShopGroupManange", null, new { target = "#main", @class = "button6" })*@        
     @* @Html.ActionLink("删除用户", "DeleteUser", "UsersManage", null, new { target = "#main", @class = "button4" })*@
    
  
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr>
                <th></th>
                <th>@Html.DisplayNameForSerialNum() </th>        
                <th>排班模板名称</th>
                <th>部门</th>
                <th>模板类型</th>
                <th>特定日期</th>
                <th>是否有效</th>
                <th>更新有效性</th>
                <th>是否历史</th>
                <th>下属班组</th>
                <th>操作</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody> 
            @{
    int i = Model.Pager.FristDataPos;    
    }
    @foreach (var item in Model)
    {
<tr>
 <td>@Html.CheckBoxButton(item.ID)</td>
<td>@(i++) </td>
<td>@Html.DisplayValueFor(item, it => it.ShopTempletName)</td>
<td>@Html.DisplayValueFor(item, it => it._Kf_DepartMent)</td>
<td>
@Html.DisplayValueFor(item, it => it.ShopTempletTypeID)
</td>
<td>
@{
        if (item.ShopTempletTypeID == _ShopTempletType.特定日期)
        { 
            @Html.DisplayValueFor(item, it => it.SpecialDate)
        }
        else
        { 
            @Html.Raw("无")
        }    
 }

</td>
<td>
@Html.DisplayValueFor(item, it => it.isValid)
</td>
 <td>
 @Html.ActionSubmitButton("checkBtn", "更新" + item.ID.ToString().Trim(), new { id = "checkBtn", @class = "button" })
 </td>
<td>
@Html.DisplayValueFor(item, it => it.isExpire)
</td>
<td>
<table>
  @{//把相应的模板的班组列出来根据模板编号
        ShopTempletDetailsRepository shopTempletDetailRepo = new ShopTempletDetailsRepository();
        List<ShopTempletDetails> listShopTempletDetails = shopTempletDetailRepo.GetAll()
            .Where(it => it._ShopTemplet == item)
            .ToList();
        if (listShopTempletDetails.Count() == 0)
        { 
          <tr>
                 <td>
                @Html.Raw("无")
                </td>
            </tr>
        }
        else
        {
            for (i = 0; i < listShopTempletDetails.Count(); i++)
            { 
               <tr>
                 <td>
                @Html.Raw(listShopTempletDetails.ElementAt(i)._ShopGroup.ShopGroupName)
                </td>
                 <td>
                @Html.Raw(listShopTempletDetails.ElementAt(i)._ShopGroup.WorkDayOrNight.ToString())
                </td>
                 <td>
                 @Html.Raw(listShopTempletDetails.ElementAt(i)._ShopGroup.ContentShops)
                 </td>
              </tr>
            }
        }  
    }   
</table>
</td>
<td> 
   <a data-opt="add" class="add_temps" href="/admin/ShopGroupManange/Add_ShopTempletDetail?id=@item.ID">班组添加或修改</a>
</td> 
<td> 
 <a data-opt="add" class="button6" href="/admin/ShopGroupManange/AddShopTemplet?id=@item.ID">修改</a>
</td> 
</tr>
    }
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>    
}