hkkf.web/Areas/Admin/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Bibliography;
using hkkf.Repositories;
using hkkf.Models;
using hkkf.web.Common;
using JieNuo.Data;
using JieNuo.Data.Exceptions;
using hkkf.web.Areas.Service.Common;

namespace hkkf.web.Areas.Admin.Controllers
{
    [NavigationRoot("财务管理")]
    [SmartAuthorize]
    [SmartMasterPage]
    public class PayController : Controller
    {
        PayRecordsRepository PayRecordsRepo = new PayRecordsRepository();
        PayRequireRecordsRepository PayRequireRecordRepo = new PayRequireRecordsRepository();
        //PayRecordManageIndex
        //实收款管理
        public ActionResult PayRecordManageIndex(QueryInfo queryInfo, int[] ids, string name, string alertMessage, string subAction)
        {
            ShopRepository shopRepo = new ShopRepository();
            PagedData<Shop> data = shopRepo.GetData(queryInfo,null,name,this.Users().DepartMent);
            return View(data);
        }

        public ActionResult PayRecordIndex(QueryInfo queryInfo, int[] ids, string name, string alertMessage, string Year,string Month)
        {
            string localYear;
            string localMonth;
            if (Year.IsNullOrEmpty())
            {
                localYear = System.DateTime.Now.Year.ToString().Trim();
            }
            else
            {
                localYear = Year;
            }
            if (Month.IsNullOrEmpty())
            {
                localMonth = System.DateTime.Now.Month.ToString().Trim();
            }
            else
            {
                localMonth = Month;
            }
            ViewData["Year"] = localYear;
            ViewData["Month"] = localMonth;
            ViewData["baseSum"] = this.PayRecordsRepo.GetPayRecordsSum(_PayType.基础服务费, localYear, localMonth);
            ViewData["tiChengSum"] = this.PayRecordsRepo.GetPayRecordsSum(_PayType.提成, localYear, localMonth);
            ViewData["totalSum"] = Convert.ToInt32(ViewData["baseSum"]) + Convert.ToInt32(ViewData["tiChengSum"]);

            //ViewData["baseRequireSum"] = this.PayRequireRecordRepo.GetPayRequireRecordsSum(_PayType.基础服务费, localYear, localMonth);
            //ViewData["tiChengRequireSum"] = this.PayRequireRecordRepo.GetPayRequireRecordsSum(_PayType.提成, localYear, localMonth);
            //ViewData["totalRequireSum"] = Convert.ToInt32(ViewData["baseRequireSum"]) + Convert.ToInt32(ViewData["tiChengRequireSum"]);
            PagedData<PayRecords> data = this.PayRecordsRepo.GetPayRecords(queryInfo,this.Users().DepartMent, name,localYear,localMonth);
            return View(data);
        }
        public ActionResult PayRequireRecordIndex(QueryInfo queryInfo, int[] ids, string name, string alertMessage, string Year, string Month)
        {
            string localYear;
            string localMonth;
            if (Year.IsNullOrEmpty())
            {
                localYear = System.DateTime.Now.Year.ToString().Trim();
            }
            else
            {
                localYear = Year;
            }
            if (Month.IsNullOrEmpty())
            {
                localMonth = "全部";
            }
            else
            {
                localMonth = Month;
            }
            ViewData["Year"] = localYear;
            ViewData["Month"] = localMonth;

            ViewData["DefaultDepartMent"] = this.Users().DepartMent;
          

            ViewData["baseSum"] = this.PayRequireRecordRepo.GetPayRequireRecordsSum(_PayType.基础服务费, localYear, localMonth);
            ViewData["tiChengSum"] = this.PayRequireRecordRepo.GetPayRequireRecordsSum(_PayType.提成, localYear, localMonth);
            ViewData["totalSum"] = Convert.ToInt32(ViewData["baseSum"]) + Convert.ToInt32(ViewData["tiChengSum"]);
            PagedData<PayRequireRecords> data = this.PayRequireRecordRepo.GetPayRequireRecords(queryInfo,this.Users().DepartMent, name, localYear, localMonth);
            return View(data);
        }

        //deletePayRecord
        public ActionResult deletePayRecord(string id)
        {
            this.PayRecordsRepo.Delete(Convert.ToInt32(id));
            return Json(new { state = true, message = "操作成功！" });
        }
        public ActionResult AddPayBaseRecord(string id,string shopID)
        {
            //shopID不为空的时候是添加，为空的时候是修改。
            //ShopID,PayTypeID,PayDate,SaleVolume,PayNum,NextPayDate,NextPayNum,DemandUserID,ConfirmUserID
            //取出数据来做DROPDOWNLIST的传递。  
            if (id != null)
            {
                PayRecords PayRecord = this.PayRecordsRepo.GetByDatabaseID(Convert.ToInt32(id));
                ViewBag.Edit = "1";
                return View(PayRecord);
            }
            ShopRepository shopRepo=new ShopRepository();
            Shop shop=shopRepo.GetByDatabaseID(Convert.ToInt32(shopID));
            ViewData["shopID"] = shopID;
            PayRecords payRecord = new PayRecords();
            payRecord.PayDate = System.DateTime.Today;           
            switch(shop._PayCircle)
            {
                case _PayCircle.月付:
                    payRecord.NextPayDate = System.DateTime.Today.AddDays(30);
                    payRecord.PayNum = shop.PriceByMonth;
                    payRecord.NextPayNum = shop.PriceByMonth;
                    break;
                case _PayCircle.季付:
                    payRecord.NextPayDate = System.DateTime.Today.AddDays(90);
                    payRecord.PayNum = shop.PriceByMonth*3;
                    payRecord.NextPayNum = shop.PriceByMonth*3;
                    break;
                case _PayCircle.半年:
                    payRecord.NextPayDate = System.DateTime.Today.AddDays(180);
                    payRecord.PayNum = shop.PriceByMonth*6;
                    payRecord.NextPayNum = shop.PriceByMonth*6;
                    break;
                case _PayCircle.一年:
                    payRecord.NextPayDate = System.DateTime.Today.AddDays(365);
                    payRecord.PayNum = shop.PriceByMonth*12;
                    payRecord.NextPayNum = shop.PriceByMonth*12;
                    break;
            }        
            return View(payRecord);
        }
        [HttpPost]
        public ActionResult AddPayBaseRecord(string PayDate, string PayNum, string NextPayDate,string NextPayNum,string shopID, int? id)
        {
            if (Convert.ToInt32(PayNum)<=0)
                return Json(new { state = false, message = "付款金额不得小于等于0！" });
            if (Convert.ToInt32(NextPayNum) <= 0)
                return Json(new { state = false, message = " 下次付款金额不得小于等于0！" });
            if (NextPayDate.ToDateTime()<=PayDate.ToDateTime())
                return Json(new { state = false, message = " 下次时间不得早于本次付款时间！" });
            PayRecords payRecord = new PayRecords();
            if (id != null && id.Value > 0)
            {
                payRecord = this.PayRecordsRepo.GetByDatabaseID(Convert.ToInt32(id));
            }
            try
            {
                //赋值                
                
                payRecord._PayType = _PayType.基础服务费;
               
                payRecord.PayDate = PayDate.ToDateTime();
                payRecord.PayNum = PayNum.ToInt();
                payRecord.SaleVolume = 0;
                payRecord.UpdateTime = System.DateTime.Now;
                payRecord.Year = PayDate.ToDateTime().Year;
                payRecord.Month = PayDate.ToDateTime().Month;
                payRecord.NextPayNum = NextPayNum.ToInt();
                payRecord.NextPayDate = NextPayDate.ToDateTime();                
                //保存
                PayRequireRecordsRepository payRequireRecordsRepo = new PayRequireRecordsRepository();
                if (id != null && id.Value > 0)
                {
                    payRecord.ConfirmUser = payRecord._Shop.MainKfUser;
                    payRecord.DemandUser = payRecord._Shop.MainKfUser;
                    this.PayRecordsRepo.Update(payRecord);
                    //根据PayRecords更新PayRequireRecords
                    payRequireRecordsRepo.AddPayRequireRecords(payRecord);
                }
                else
                {
                    ShopRepository shopRepo = new ShopRepository();
                    payRecord._Shop = shopRepo.GetByDatabaseID(Convert.ToInt32(shopID));
                    payRecord.ConfirmUser = payRecord._Shop.MainKfUser;
                    payRecord.DemandUser = payRecord._Shop.MainKfUser;
                    this.PayRecordsRepo.Save(payRecord);
                    payRequireRecordsRepo.AddPayRequireRecords(payRecord);
                }            
                return Json(new { state = true, message = "操作成功！" });
            }
            catch (RuleException ex)
            {
                throw new RuleException(ex.Message, ex);
            }            
        }

        public ActionResult AddPayTiChengRecord(string id, string shopID)
        {
            //shopID不为空的时候是添加，为空的时候是修改。
            //ShopID,PayTypeID,PayDate,SaleVolume,PayNum,NextPayDate,NextPayNum,DemandUserID,ConfirmUserID
            //取出数据来做DROPDOWNLIST的传递。  

            if (id != null)
            {
                PayRecords PayRecord = this.PayRecordsRepo.GetByDatabaseID(Convert.ToInt32(id));
                ViewBag.Edit = "1";
                return View(PayRecord);
            }
            ShopRepository shopRepo = new ShopRepository();
            Shop shop = shopRepo.GetByDatabaseID(Convert.ToInt32(shopID));
            ViewData["shopID"] = shopID;
            PayRecords payRecord = new PayRecords();
            payRecord.PayNum = 0;
            payRecord.PayDate = System.DateTime.Today;
            payRecord.NextPayNum = 0;
            payRecord.NextPayDate = System.DateTime.Today.AddDays(15);
          
            return View(payRecord);
        }
        [HttpPost]

hkkf.web/Areas/Admin/Views/Pay/AddPayBaseRecord.cshtml
@using hkkf.Models
@model hkkf.Models.PayRecords


@{
    ViewBag.Title = "添加付款记录";
    Layout = null;   
}

<form method="post" action="@this.Request.Url.AbsoluteUri" class="operatInfoDiv">
    <table cellspacing="2" cellpadding="0"  >
   @Html.Hidden("shopID",ViewData["shopID"])
               <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.PayDate)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.PayDate)
                   </td>
                </tr>              
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.PayNum)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.PayNum)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.NextPayDate)：</p>
                    </td>
                    <td colspan="1"align=left>
                         @Html.ValueBoxFor(model => model.NextPayDate)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.NextPayNum)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.NextPayNum)
                   </td>
                </tr>          
    </table>
</form>

hkkf.web/Areas/Admin/Views/Pay/AddPayTiChengRecord.cshtml
@using hkkf.Models
@model hkkf.Models.PayRecords


@{
    ViewBag.Title = "添加付款记录";
    Layout = null;   
}

<form method="post" action="@this.Request.Url.AbsoluteUri" class="operatInfoDiv">
    <table cellspacing="2" cellpadding="0"  >
   @Html.Hidden("shopID",ViewData["shopID"])
                  <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.PayDate)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.PayDate)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.SaleVolume)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.SaleVolume)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.PayNum)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.PayNum)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.NextPayDate)：</p>
                    </td>
                    <td colspan="1"align=left>
                         @Html.ValueBoxFor(model => model.NextPayDate)
                   </td>
                </tr>
                <tr> 
                    <td width="17%" align="right">
                         <p>@Html.DisplayNameFor(model => model.NextPayNum)：</p>
                    </td>
                    <td colspan="1"align=left>
                        @Html.ValueBoxFor(model => model.NextPayNum)
                   </td>
                </tr>          
    </table>
</form>

hkkf.web/Areas/Admin/Views/Pay/PayRecordIndex.cshtml
@model JieNuo.Data.PagedData<hkkf.Models.PayRecords>

@{
    ViewBag.Title = "店铺类别管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
 </script>


@Html.NavigationBar("付款记录管理", "付款记录管理")
@using (Ajax.JQueryBeginForm("PayRecordIndex", "Pay", new JQueryOptions { UpdateTarget = "#main" }))
 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
                <th>
                安排时间：从
            </th>
            <td>
            @{
    List<SelectListItem> list = new List<SelectListItem> {
                new SelectListItem { Text = "2016", Value = "2016" },
                new SelectListItem { Text = "2015", Value = "2015" } };
                }
              @Html.DropDownList("Year",list,this.ViewData["Year"])  
            </td>
            <th>
                至
            </th>
            <td>
            @{
            List<SelectListItem> listMonth = new List<SelectListItem> {
                new SelectListItem { Text = "1", Value = "1" },
                new SelectListItem { Text = "2", Value = "2" },
                 new SelectListItem { Text = "3", Value = "3" },
                  new SelectListItem { Text = "4", Value = "4" },
                   new SelectListItem { Text = "5", Value = "5" },
                    new SelectListItem { Text = "6", Value = "6" },
                     new SelectListItem { Text = "7", Value = "7" },
                      new SelectListItem { Text = "8", Value = "8" },
                       new SelectListItem { Text = "9", Value = "9" },
                        new SelectListItem { Text = "10", Value = "10" },
                         new SelectListItem { Text = "11", Value = "11" },
                          new SelectListItem { Text = "12", Value = "12" },            
                    };
                }                
              @Html.DropDownList("Month", listMonth, this.ViewData["Month"])  
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
            </td>
        </tr>
    </table> 
    <table>
    <tr>
    <td>
   @this.ViewData["Year"]年
   @this.ViewData["Month"]月
    </td>
    <td>基础服务费实收总计 @ViewData["baseSum"]</td>
    <td>提成实收总计 @ViewData["tiChengSum"]</td>
    <td>总计 @ViewData["totalSum"]</td>
    </tr>
    </table>
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr> 
                <th>@Html.DisplayNameForSerialNum()</th>        
                <th>店铺</th>
                <th>部门</th>
                <th>年</th>
                <th>月</th>
                <th>付款类型</th>
                <th>付款日期</th>
                <th>付款金额</th>
                <th>下次付款日期</th>
                <th>下次付款金额</th>
                <th>催款人</th>
                <th>确认人</th>                
            </tr>
        </thead>
        <tbody> 
            @{
                
            int i = Model.Pager.FristDataPos;                 
  
    }
    @foreach (var item in Model)
    {
<tr>
<td>@(i++) </td>  
<td>@Html.DisplayValueFor(item, it => it._Shop)</td>
<td>@Html.Raw(item._Shop._Kf_DepartMent.ToString())</td>
<td>@Html.Raw(item.Year.ToString())</td>
<td>@Html.Raw(item.Month.ToString())</td>
<td>@Html.DisplayValueFor(item, it => it._PayType)</td>
<td>@Html.DisplayValueFor(item, it => it.PayDate)</td>
<td>@Html.DisplayValueFor(item, it => it.PayNum)</td>
<td>@Html.DisplayValueFor(item, it => it.NextPayDate)</td>
<td>@Html.DisplayValueFor(item, it => it.NextPayNum)</td>
<td>@Html.DisplayValueFor(item, it => it.DemandUser)</td>
<td>@Html.DisplayValueFor(item, it => it.ConfirmUser)</td>
</tr>
    }
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>    
}

hkkf.web/Areas/Admin/Views/Pay/PayRecordManageIndex.cshtml
@using System
@using DocumentFormat.OpenXml.Office.CustomUI
@using hkkf.Models
@using hkkf.Repositories
@model JieNuo.Data.PagedData<hkkf.Models.Shop>

@{
    ViewBag.Title = "店铺类别管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
 </script>


@Html.NavigationBar("付款记录管理", "付款记录管理")
@using (Ajax.JQueryBeginForm("PayRecordManageIndex", "Pay", new JQueryOptions { UpdateTarget = "#main" })) 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
            </td>
        </tr>
    </table>
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr> 
                <th>@Html.DisplayNameForSerialNum() </th>        
                <th>店铺</th>
                <th>部门</th>
                <th>月服务费</th>
                <th>周期</th>
                <th>提成点</th>
                <th>固定提成</th>
                <th>备注</th>
                <th>销售</th>
                <th>主客服</th>
                <th>付款类型 日期 金额 下次付款日期 下次付款金额</th>
                <th>店铺状态</th>
            </tr>
        </thead>
        <tbody> 
            @{
    PayRecordsRepository payRecordsRepo = new PayRecordsRepository();
    int i = Model.Pager.FristDataPos;  
             //  值班类型 组数 月费用付款周期 销售提成 所属部门销售人员管理人员主客服  
    }
    @foreach (var item in Model)
    {
<tr>
<td>@(i++) </td>  
<td>@Html.Raw(item.Name)</td>
<td>@Html.Raw(item._Kf_DepartMent.ToString())</td>
<td>@Html.Raw(item.PriceByMonth.ToString())</td>
<td>@Html.Raw(item._PayCircle.ToString())</td>
<td>@Html.Raw(item.TiChengRate.ToString())</td>
<td>@Html.Raw(item.FixedTiCheng.ToString())</td>
<td>@Html.Raw(item.Beizhu)</td>
<td>@Html.Raw(item.SaleUser.ToString())</td>
<td>@Html.Raw(item.MainKfUser.ToString())</td>
<td>
<table>
<tr>
<td>
服务费
</td>
<td>
 @{
        //取出该店铺的最近4次的付款记录，在当月的可修改，不在当月的不可修改。      
        List<PayRecords> listPayRecords = payRecordsRepo.GetPayRecords(item.ID.ToString(),_PayType.基础服务费);
        if (listPayRecords.Count() == 0)
        { 
            @Html.Raw("无")
        }
        else
        {
            <table>
            @{
                foreach (var PayRecord in listPayRecords)
                { 
                    <tr>
                         <td>
                        @Html.Raw(PayRecord.PayDate.Date.ToShortDateString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.PayNum.ToString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.NextPayDate.Date.ToShortDateString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.NextPayNum.ToString())                    
                        </td>
                        <td>   <a data-opt="add" class="add_temps" href="/admin/Pay/AddPayBaseRecord?id=@PayRecord.ID">修改</a></td>  
                        <td> <a data-opt="delete" data-msg="确定是否删除？"  class="" href="/admin/Pay/deletePayRecord?id=@PayRecord.ID">删除</a></td> 
                    </tr>
                }
                }
                </table>
            }
         }
</td>
<td>
  <a data-opt="add" class="add_temps" href="/admin/Pay/AddPayBaseRecord?shopID=@item.ID">添加</a>
</td>
</tr>
<tr>
<td>
提成
</td>
<td>
 @{
        //取出该店铺的最近4次的付款记录，在当月的可修改，不在当月的不可修改。
        List<PayRecords> listPayTiChengRecords = payRecordsRepo.GetPayRecords(item.ID.ToString(),_PayType.提成);
        if (listPayTiChengRecords.Count() == 0)
        { 
            @Html.Raw("无")
        }
        else
        {
            <table>
            @{
            foreach (var PayRecord in listPayTiChengRecords)
                { 
                    <tr>                     
                           <td>
                        @Html.Raw(PayRecord.PayDate.Date.ToShortDateString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.PayNum.ToString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.NextPayDate.Date.ToShortDateString())
                        </td>
                           <td>
                        @Html.Raw(PayRecord.NextPayNum.ToString())                    
                        </td>
                        <td>   <a data-opt="add" class="add_temps" href="/admin/Pay/AddPayTiChengRecord?id=@PayRecord.ID">修改</a></td>  
                        <td> <a data-opt="delete" data-msg="确定是否删除？"  class="" href="/admin/Pay/deletePayRecord?id=@PayRecord.ID">删除</a></td> 
                    </tr>
                }
                }
                </table>
            }
         }
</td>
<td>
  <a data-opt="add" class="add_temps" href="/admin/Pay/AddPayTiChengRecord?shopID=@item.ID">添加</a>
</td>
</tr>
</table>       
</td>
<td>@Html.Raw(item.ShopStateID.ToString())</td>
</tr>
 }
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>
    
}

hkkf.web/Areas/Admin/Views/Pay/PayRequireRecordIndex.cshtml
@using System
@using System.Collections.Generic
@using System.Linq
@using System.Xml.Serialization
@using DocumentFormat.OpenXml.Spreadsheet
@using hkkf.Models
@using hkkf.Repositories
@model JieNuo.Data.PagedData<hkkf.Models.PayRequireRecords>
@{
    ViewBag.Title = "店铺类别管理";
    Layout = "~/Areas/Admin/Views/Shared/_admin.cshtml";
    
}

<script type="text/javascript">
    $(function () {
        batchMsg("deleteBtn");
        $("#deleteBtn").click(function () {
            $("#subAction").attr("value", "delete");
        });
    });
 </script>


@Html.NavigationBar("应收款管理", "应收款查询")
@using (Ajax.JQueryBeginForm("PayRequireRecordIndex", "Pay", new JQueryOptions { UpdateTarget = "#main" }))
 
{
    @Html.Hidden("subAction", "", new { id = "subAction" })
    <div class="alertMessageContainer" >@ViewBag.message</div>
    <table class="conditionTable infoTable">
        <tr>
            <th>
                店铺名：
            </th>
            <td style="width: 220px;">@Html.TextBox("Name", null, new { id = "Name" })
            </td>
                <th>
                安排时间：年
            </th>
            <td>
            @{
    List<SelectListItem> list = new List<SelectListItem> {
                new SelectListItem { Text = "2016", Value = "2016" },
                new SelectListItem { Text = "2015", Value = "2015" } };
                }
              @Html.DropDownList("Year",list,this.ViewData["Year"])  
            </td>
            <th>
                月
            </th>
            <td>
            @{
            List<SelectListItem> listMonth = new List<SelectListItem> {
                new SelectListItem { Text = "全部", Value = "全部" },
                new SelectListItem { Text = "1", Value = "1" },
                new SelectListItem { Text = "2", Value = "2" },
                 new SelectListItem { Text = "3", Value = "3" },
                  new SelectListItem { Text = "4", Value = "4" },
                   new SelectListItem { Text = "5", Value = "5" },
                    new SelectListItem { Text = "6", Value = "6" },
                     new SelectListItem { Text = "7", Value = "7" },
                      new SelectListItem { Text = "8", Value = "8" },
                       new SelectListItem { Text = "9", Value = "9" },
                        new SelectListItem { Text = "10", Value = "10" },
                         new SelectListItem { Text = "11", Value = "11" },
                          new SelectListItem { Text = "12", Value = "12" },            
                    };
                }                
              @Html.DropDownList("Month", listMonth, this.ViewData["Month"])  
            </td>            
            <td style="width: 220px;">@Html.ActionSubmitButton("queryBtn", "查询", new { id = "queryBtn", @class = "button" })
            </td>
        </tr>
    </table> 
    <table>
    <tr>
    <td>
   @this.ViewData["Year"]年
   @this.ViewData["Month"]月
    </td>
    <td>基础服务费应收总计 @ViewData["baseSum"]</td>
    <td>提成应收总计 @ViewData["tiChengSum"]</td>
    <td>合计应收总计 @ViewData["totalSum"]</td>
    </tr>
    </table>
  <div class="grid">
    <table class="dataTable">
    <thead>
            <tr> 
                <th>@Html.DisplayNameForSerialNum() </th>        
                <th>店铺</th>
                <th>部门</th>
                <th>年</th>
                <th>月</th>
                <th>应付款类型</th>              
                <th>应付款日期</th>
                <th>应付款金额</th>
                <th>主客服</th>    
                <th>店铺状态</th>             
            </tr>
        </thead>
        <tbody> 
            @{
                
                int i = Model.Pager.FristDataPos;                 
  
    }
    @foreach (var item in Model)
    {
<tr>
<td>@(i++) </td>  
<td>@Html.DisplayValueFor(item, it => it._Shop)</td>
<td>@Html.Raw(item._Shop._Kf_DepartMent.ToString())</td>
<td>@Html.Raw(item.Year.ToString())</td>
<td>@Html.Raw(item.Month.ToString())</td>
<td>@Html.Raw(item._PayType.ToString())</td>
<td>@Html.Raw(item.PayRequireDate.ToShortDateString())</td>
<td>@Html.Raw(item.PayRequireNum.ToString())</td>
<td>@Html.Raw(item._Shop.MainKfUser.ToString())</td>
<td>@Html.Raw(item._Shop.ShopStateID.ToString())</td>
</tr>
    }
</tbody>
</table>
@Html.Pager(Model.Pager)
</div>
    
}